#############################################################################
# Makefile for building: ThreeAces-qt
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  ThreeAces.pro
# Template: app
# Command: C:\Qt\5.6.0\bin\qmake.exe "USE_UPNP=0" -o Makefile ThreeAces.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:\Qt\5.6.0\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: ThreeAces.pro ../QT/5.6.0/mkspecs/win32-g++/qmake.conf ../QT/5.6.0/mkspecs/features/spec_pre.prf \
		../QT/5.6.0/mkspecs/qdevice.pri \
		../QT/5.6.0/mkspecs/features/device_config.prf \
		../QT/5.6.0/mkspecs/common/angle.conf \
		../QT/5.6.0/mkspecs/qconfig.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_axbase.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_axbase_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_axcontainer.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_axserver.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_axserver_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_bluetooth.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_clucene_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_concurrent.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_core.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_core_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_enginio.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_enginio_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_gui.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_gui_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_help.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_help_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_multimedia.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_network.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_network_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_nfc.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_nfc_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_positioning.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_positioning_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_printsupport.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_qml.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_qml_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_script.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_script_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_scripttools.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_sensors.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_sensors_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_serialbus.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_serialport.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_serialport_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_sql.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_sql_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_svg.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_svg_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_testlib.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_testlib_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_uiplugin.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_uitools.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_uitools_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_webchannel.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_websockets.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_websockets_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_widgets.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_widgets_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_winextras.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_winextras_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_xml.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_xml_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_lib_zlib_private.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_dsengine.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qdds.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qicns.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qico.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qminimal.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qsvg.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtga.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtiff.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qwbmp.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qwebp.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_qwindows.pri \
		../QT/5.6.0/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../QT/5.6.0/mkspecs/features/qt_functions.prf \
		../QT/5.6.0/mkspecs/features/qt_config.prf \
		../QT/5.6.0/mkspecs/features/win32/qt_config.prf \
		../QT/5.6.0/mkspecs/win32-g++/qmake.conf \
		../QT/5.6.0/mkspecs/features/spec_post.prf \
		../QT/5.6.0/mkspecs/features/exclusive_builds.prf \
		../QT/5.6.0/mkspecs/features/default_pre.prf \
		../QT/5.6.0/mkspecs/features/win32/default_pre.prf \
		../QT/5.6.0/mkspecs/features/resolve_config.prf \
		../QT/5.6.0/mkspecs/features/exclusive_builds_post.prf \
		../QT/5.6.0/mkspecs/features/default_post.prf \
		../QT/5.6.0/mkspecs/features/win32/rtti.prf \
		../QT/5.6.0/mkspecs/features/precompile_header.prf \
		../QT/5.6.0/mkspecs/features/warn_on.prf \
		../QT/5.6.0/mkspecs/features/qt.prf \
		../QT/5.6.0/mkspecs/features/resources.prf \
		../QT/5.6.0/mkspecs/features/moc.prf \
		../QT/5.6.0/mkspecs/features/uic.prf \
		../QT/5.6.0/mkspecs/features/win32/windows.prf \
		../QT/5.6.0/mkspecs/features/testcase_targets.prf \
		../QT/5.6.0/mkspecs/features/exceptions.prf \
		../QT/5.6.0/mkspecs/features/yacc.prf \
		../QT/5.6.0/mkspecs/features/lex.prf \
		ThreeAces.pro \
		../QT/5.6.0/lib/qtmaind.prl \
		../QT/5.6.0/lib/Qt5PrintSupport.prl \
		../QT/5.6.0/lib/Qt5Widgets.prl \
		../QT/5.6.0/lib/Qt5Gui.prl \
		../QT/5.6.0/lib/Qt5Network.prl \
		../QT/5.6.0/lib/Qt5Core.prl \
		../QT/5.6.0/plugins/printsupport/windowsprintersupport.prl \
		../QT/5.6.0/plugins/platforms/qwindows.prl \
		../QT/5.6.0/plugins/imageformats/qdds.prl \
		../QT/5.6.0/plugins/imageformats/qicns.prl \
		../QT/5.6.0/plugins/imageformats/qico.prl \
		../QT/5.6.0/plugins/imageformats/qtga.prl \
		../QT/5.6.0/plugins/imageformats/qtiff.prl \
		../QT/5.6.0/plugins/imageformats/qwbmp.prl \
		../QT/5.6.0/plugins/imageformats/qwebp.prl \
		../QT/5.6.0/plugins/bearer/qgenericbearer.prl \
		../QT/5.6.0/plugins/bearer/qnativewifibearer.prl
	$(QMAKE) "USE_UPNP=0" -o Makefile ThreeAces.pro
../QT/5.6.0/mkspecs/features/spec_pre.prf:
../QT/5.6.0/mkspecs/qdevice.pri:
../QT/5.6.0/mkspecs/features/device_config.prf:
../QT/5.6.0/mkspecs/common/angle.conf:
../QT/5.6.0/mkspecs/qconfig.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_axbase.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_axbase_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_axcontainer.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_axcontainer_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_axserver.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_axserver_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_bluetooth.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_clucene_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_concurrent.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_concurrent_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_core.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_core_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_enginio.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_enginio_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_gui.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_gui_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_help.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_help_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_multimedia.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_multimedia_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_network.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_network_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_nfc.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_nfc_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_platformsupport_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_positioning.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_positioning_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_printsupport.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_printsupport_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_qml.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_qml_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_script.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_script_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_scripttools.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_scripttools_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_sensors.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_sensors_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_serialbus.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_serialbus_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_serialport.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_serialport_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_sql.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_sql_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_svg.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_svg_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_testlib.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_testlib_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_uiplugin.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_uitools.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_uitools_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_webchannel.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_webchannel_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_websockets.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_websockets_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_widgets.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_widgets_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_winextras.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_winextras_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_xml.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_xml_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../QT/5.6.0/mkspecs/modules/qt_lib_zlib_private.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_dsengine.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qdds.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qicns.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qico.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qminimal.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qsvg.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qsvgicon.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtga.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtiff.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qttinycanbus.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qwbmp.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qwebp.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_qwindows.pri:
../QT/5.6.0/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../QT/5.6.0/mkspecs/features/qt_functions.prf:
../QT/5.6.0/mkspecs/features/qt_config.prf:
../QT/5.6.0/mkspecs/features/win32/qt_config.prf:
../QT/5.6.0/mkspecs/win32-g++/qmake.conf:
../QT/5.6.0/mkspecs/features/spec_post.prf:
../QT/5.6.0/mkspecs/features/exclusive_builds.prf:
../QT/5.6.0/mkspecs/features/default_pre.prf:
../QT/5.6.0/mkspecs/features/win32/default_pre.prf:
../QT/5.6.0/mkspecs/features/resolve_config.prf:
../QT/5.6.0/mkspecs/features/exclusive_builds_post.prf:
../QT/5.6.0/mkspecs/features/default_post.prf:
../QT/5.6.0/mkspecs/features/win32/rtti.prf:
../QT/5.6.0/mkspecs/features/precompile_header.prf:
../QT/5.6.0/mkspecs/features/warn_on.prf:
../QT/5.6.0/mkspecs/features/qt.prf:
../QT/5.6.0/mkspecs/features/resources.prf:
../QT/5.6.0/mkspecs/features/moc.prf:
../QT/5.6.0/mkspecs/features/uic.prf:
../QT/5.6.0/mkspecs/features/win32/windows.prf:
../QT/5.6.0/mkspecs/features/testcase_targets.prf:
../QT/5.6.0/mkspecs/features/exceptions.prf:
../QT/5.6.0/mkspecs/features/yacc.prf:
../QT/5.6.0/mkspecs/features/lex.prf:
ThreeAces.pro:
../QT/5.6.0/lib/qtmaind.prl:
../QT/5.6.0/lib/Qt5PrintSupport.prl:
../QT/5.6.0/lib/Qt5Widgets.prl:
../QT/5.6.0/lib/Qt5Gui.prl:
../QT/5.6.0/lib/Qt5Network.prl:
../QT/5.6.0/lib/Qt5Core.prl:
../QT/5.6.0/plugins/printsupport/windowsprintersupport.prl:
../QT/5.6.0/plugins/platforms/qwindows.prl:
../QT/5.6.0/plugins/imageformats/qdds.prl:
../QT/5.6.0/plugins/imageformats/qicns.prl:
../QT/5.6.0/plugins/imageformats/qico.prl:
../QT/5.6.0/plugins/imageformats/qtga.prl:
../QT/5.6.0/plugins/imageformats/qtiff.prl:
../QT/5.6.0/plugins/imageformats/qwbmp.prl:
../QT/5.6.0/plugins/imageformats/qwebp.prl:
../QT/5.6.0/plugins/bearer/qgenericbearer.prl:
../QT/5.6.0/plugins/bearer/qnativewifibearer.prl:
qmake: FORCE
	@$(QMAKE) "USE_UPNP=0" -o Makefile ThreeAces.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) C:\ThreeAces\src\leveldb\libleveldb.a;
	-$(DEL_FILE) cd
	-$(DEL_FILE) C:\ThreeAces\src\leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) clean
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\ThreeAces\threeaces-qt_plugin_import.cpp

C:/ThreeAces/src/leveldb/libleveldb.a: FORCE

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
